---
data:
    name: "{{ __sanitized_project_name__ | replace('-', '_') }}" 
    title: "{{ project_title }}"
    description: "{{ description }}" 
    keywords: ["{{ metric_keyword }}"]  ## Metric keyword to make this dataset reachable for other projects/benchmark components.
script: "src/run_{{__sanitized_project_name__}}.R" ## change for .py if you are using a py script
benchmark_name: "{{ benchmark_name }}" ## Name of the omnibenchmark to link this project with.
inputs:
  keywords: [" "] ## Keyword(s) of the methods output to import for evaluation. 
  ## File types and patterns to use for automatic detection. 
  ## Example
  # files: ["input_file1", "input_file2"]
  # prefix:
  #   input_file_name1: "_INPUT1_"
  #   input_file_name2: "_INPUT2_"
  #   ...
outputs:
  ## Automatically defined. To change only if you wish specific output names. 
  template: "data/${name}/${name}_${unique_values}_${out_name}.${out_end}" 
  files:
    metric_res: 
        end: "json"
