---
data:
    "{{ __sanitized_project_name__ | replace('-', '_') }}"
    title: "{{ project_title }}"
    description: "{{ description }}"
    keywords: ["{{ metric_keyword }}"]
script: "src/generate_metric_info.py"
benchmark_name: "{{ benchmark_name }}"
outputs:
    files:
        metric_info: 
            end: "json"
    file_mapping:
        mapping1:
          output_files:
            metric_info: "data/{{ sanitized_project_name }}/{{ sanitized_project_name }}_info.json"
