---
data:
    "{{ __sanitized_project_name__ | replace('-', '_') }}"
    title: "{{ project_title }}"
    description: "Parsed summary of metric files for {{ benchmark_name }} "
    keywords: ["{{ summary_keyword }}"]  ## <---- a keyword for this summary project
benchmark_name: "{{ benchmark_name }}" ## <---- Name of the omnibenchmark to link this project with.
script: "src/benchmark_summary.R"
inputs: ## Leave everything below as it is --------------------------------------------------------
    input_files:
        import_this_dataset:
            res_files: "data/metric_result_file_sparql.json"
            info_files: "data/metric_result_file_sparql_info.json"
outputs:
    template: "data/${name}/${name}_${out_name}.${out_end}"
    files:
        summary_parsed: 
            end: "json"