---
data:
    name: "{{ sanitized_project_name }}"
    title: "{{ project_title }}"
    description: "{{ description }}"
    keywords: ["{{ parameter_keyword }}"] ## Parameter keyword to make this dataset reachable for other projects/benchmark components.
script: "src/generate_parameter_file.py" ## Default.
sanitized_project_name: "{{ sanitized_project_name }}" ## Name of the omnibenchmark to link this project with.
outputs:
    ## This section defines the parameter space. It normally doesn't need any modification. 
    files:
        param_json:
            end: ".json"
    file_mapping:
        mapping1:
            output_files:
                param_json: "data/{{  sanitized_project_name  }}/all_parameter.json"
            input_files: 
            parameter: 
