---
data:
    name: "{{ sanitized_project_name }}"
    title: "{{ project_title }}"
    description: "{{ description }}"
    keywords: ["{{ dataset_keyword }}"] ## Dataset keyword to make this dataset reachable for other projects/ benchmarks components.
script: "src/{{ sanitized_project_name }}.R"
outputs:
    template: "data/${name}/${name}_${out_name}.${out_end}"
    files:
        ## File to use for automatic detection and the pattern to recognize them. 
        ## Should correspond to the argument names in your script.
        ## EXAMPLE:
        # data_file1:           ## same as your script's args
        #     end: "FILE1_END"  ## file extension 
        # data_file2:
        #     end: "FILE2_END"
        #...
sanitized_project_name: "{{ sanitized_project_name }}" ## Name of the omnibenchmark to link this project with.
